print("# REYES MEZA ALAN EDUARDO : EXAMEN PRIMER PARCIAL # NOMBRE DE ACTIVIDAD Y DATOS DEL PROGRAMADOR")

print(" ")  # ESPACIO PARA AGREGAR LA INFO DE PRACTICA Y PROGRAMADOR

# Capturar el nombre y el apellido
apellido_paterno = input("¿Cuál es tu apellido paterno?: ")  # solicita tu apellido paterno
apellido_materno = input("¿Cuál es tu apellido materno?: ")  # solicita tu apellido materno
nombre = input("¿Cuál es tu nombre?: ")  # solicita tu nombre 

print(" ") #espacio

# Desplegar cada una de las variables que conforman el nombre
print("Apellido Paterno:", apellido_paterno)  # despliega tu apellido paterno
print("Apellido Materno:", apellido_materno)  # despliega tu apellido materno
print("Nombre:", nombre)  # despliega tu nombre 

# Desplegar el nombre comenzando por el apellido paterno
nombre_completo = f"{apellido_paterno} {apellido_materno} {nombre}"  # nombre completo

print(" ") # espacio

# Mostrar el nombre completo
print("Nombre completo:", nombre_completo) #muestra tu nombre completo

print(" ") #espacio

# Convertir a mayúsculas
nombre_completo_mayusculas = nombre_completo.upper()  # convierte una cadena a MAYÚSCULAS
print("Nombre completo en mayúsculas:", nombre_completo_mayusculas)  # despliega nombre completo en MAYÚSCULAS





